# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2ee0a484c46b64e1ebc1d19de1412f451efb8294cbc0f011c7fd89c959ee11d22dded3cae0e08beead62a919fefbd71908aad8a154e7131b7e3fa6cdd3b2b01

test:
  secret_key_base: 245152864b443a7d35081ffaebe06ff87132fbc569be9a2ac06f1ee8d2583cf96ab4ef5993044bed07ca15241eb13f11b5e7ba0ddb238a618a08b9727720bf40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
